name: Build and Deploy

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

on:
    push:
        branches:
        - master

permissions:
    contents: write

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout 🛎️
                uses: actions/checkout@v3
            -   uses: actions/setup-python@v4
                with:
                    python-version: "3.11"
            -   name: Install and Build 🔧
                run: |
                    python -m pip install --upgrade pip
                    python -m pip install -r requirements.txt
                    mkdocs build

            -   name: Deploy 🚀
                uses: JamesIves/github-pages-deploy-action@v4
                with:
                    folder: site